'use client';

import { useEffect, useRef, useState } from 'react';
import Link from 'next/link';
import { useShop } from './ShopProvider';

export default function Featured() {
  const { addToBag } = useShop();
  const [added, setAdded] = useState(false);
  const cardRef = useRef(null);

  const handleOpenRoadmap = () => {
    addToBag('A Bigger Me Roadmap Journal');
    setAdded(true);
    setTimeout(() => setAdded(false), 3500);
  };

  /* ---------- roadmap "falling into place" cinematic ----------
     One 10s pass the first time the card comes into view: the pieces hold,
     fall into place one after another, and at 8.35s the master render
     cross-fades back, so the final 1.38s is the untouched reference image. */
  useEffect(() => {
    const card = cardRef.current;
    if (!card) return;
    if (matchMedia('(prefers-reduced-motion: reduce)').matches) return;

    const stage = card.querySelector('.rm-stage');
    const master = card.querySelector('.roadmap-master-img');
    if (!stage || !master) return;

    card.dataset.rmArmed = '1';
    const layers = [...stage.querySelectorAll('img')];
    const timers = [];
    let played = false;
    const finish = () => card.classList.remove('is-playing');

    /* never open the sequence on half-decoded layers: pull them in, wait for
       the last one (or 2.5s), then run the single 10s pass */
    const decoded = () => Promise.all(layers.map(img => {
      img.loading = 'eager';
      return img.complete ? null : new Promise(res => {
        img.addEventListener('load', res, { once: true });
        img.addEventListener('error', res, { once: true });
      });
    }));

    const play = () => {
      if (played) return;
      played = true;
      card.classList.add('is-playing');
      master.addEventListener('animationend', finish, { once: true });
      timers.push(setTimeout(finish, 10600));   // safety net if the event is missed
    };

    const io = new IntersectionObserver(en => {
      if (!en[0].isIntersecting) return;
      io.disconnect();
      Promise.race([decoded(), new Promise(res => timers.push(setTimeout(res, 2500)))])
        .then(() => timers.push(setTimeout(play, 240)));  // let the reveal land first
    }, { threshold: .45 });
    io.observe(card);

    return () => {
      io.disconnect();
      timers.forEach(clearTimeout);
      card.classList.remove('is-playing');
    };
  }, []);

  return (
    <section className="featured wrap" id="collections" aria-labelledby="featuredTitle">
      <h2 id="featuredTitle" className="sr-only">A Bigger Me - My Roadmap</h2>

      <div className="featured-roadmap-card reveal" ref={cardRef}>
        {/* rm-stage: BEGIN (generated by tools/build_roadmap_animation.py) */}
        <div className="rm-stage" aria-hidden="true">
          <img className="rm-plate" src="/assets/roadmap-layers/plate.jpg" alt="" draggable="false" loading="lazy" decoding="async" />
          {/* MY ROADMAP label */}
          <img className="rm-el rm-el--label rm-el--type" src="/assets/roadmap-layers/label.png" alt="" draggable="false" loading="lazy" decoding="async" />
          {/* top navigation */}
          <img className="rm-el rm-el--nav rm-el--type" src="/assets/roadmap-layers/nav.png" alt="" draggable="false" loading="lazy" decoding="async" />
          {/* A Bigger Me headline */}
          <img className="rm-el rm-el--headline rm-el--type" src="/assets/roadmap-layers/headline.png" alt="" draggable="false" loading="lazy" decoding="async" />
          {/* supporting paragraph */}
          <img className="rm-el rm-el--copy rm-el--type" src="/assets/roadmap-layers/copy.png" alt="" draggable="false" loading="lazy" decoding="async" />
          {/* Open My Roadmap button */}
          <img className="rm-el rm-el--cta rm-el--type" src="/assets/roadmap-layers/cta.png" alt="" draggable="false" loading="lazy" decoding="async" />
          {/* Discipline Creates Freedom caption */}
          <img className="rm-el rm-el--discipline rm-el--type" src="/assets/roadmap-layers/discipline.png" alt="" draggable="false" loading="lazy" decoding="async" />
          {/* Better Things Ahead note */}
          <img className="rm-el rm-el--note" src="/assets/roadmap-layers/note.png" alt="" draggable="false" loading="lazy" decoding="async" />
          {/* pen cup and pens */}
          <img className="rm-el rm-el--pencup" src="/assets/roadmap-layers/pencup.png" alt="" draggable="false" loading="lazy" decoding="async" />
          {/* A Bigger Me journal */}
          <img className="rm-el rm-el--journal" src="/assets/roadmap-layers/journal.png" alt="" draggable="false" loading="lazy" decoding="async" />
          {/* stacked books */}
          <img className="rm-el rm-el--books" src="/assets/roadmap-layers/books.png" alt="" draggable="false" loading="lazy" decoding="async" />
          {/* pink glass orb */}
          <img className="rm-el rm-el--orb" src="/assets/roadmap-layers/orb.png" alt="" draggable="false" loading="lazy" decoding="async" />
          {/* foreground notebook */}
          <img className="rm-el rm-el--notebook" src="/assets/roadmap-layers/notebook.png" alt="" draggable="false" loading="lazy" decoding="async" />
          {/* pink pencil */}
          <img className="rm-el rm-el--pencil" src="/assets/roadmap-layers/pencil.png" alt="" draggable="false" loading="lazy" decoding="async" />
          {/* laptop */}
          <img className="rm-el rm-el--laptop" src="/assets/roadmap-layers/laptop.png" alt="" draggable="false" loading="lazy" decoding="async" />
          {/* flowering plant */}
          <img className="rm-el rm-el--plant" src="/assets/roadmap-layers/plant.png" alt="" draggable="false" loading="lazy" decoding="async" />
        </div>
        {/* rm-stage: END */}

        {/* Full width master image base (100% accurate, pristine render) */}
        <img
          src="/assets/roadmap_full.jpg"
          alt="A Bigger Me - My Roadmap"
          className="roadmap-master-img"
        />

        {/* Hotspots over PLAN, GROW, BUILD, EXPLORE (no text overlap) */}
        <nav className="roadmap-overlay-nav" aria-label="Roadmap Navigation">
          <a href="#plan" className="nav-hotspot" aria-label="Plan Section"></a>
          <a href="#grow" className="nav-hotspot" aria-label="Grow Section"></a>
          <a href="#build" className="nav-hotspot" aria-label="Build Section"></a>
          <a href="#explore" className="nav-hotspot" aria-label="Explore Section"></a>
        </nav>

        {/* Hotspot overlay over Open My Roadmap button */}
        <Link
          href="/my-roadmap"
          target="_self"
          className={`roadmap-overlay-btn ${added ? 'is-added' : ''}`}
          onClick={handleOpenRoadmap}
          aria-label="Open My Roadmap"
        >
          {added && <span className="added-badge">Added to Bag ✓</span>}
        </Link>
      </div>
    </section>
  );
}
